### PR TITLE
Implement most of the decoding and encoding of DICompileUnit

### PR DESCRIPTION
**Pull request by cocreature**
Also includes a roundtrip test for the fields that are supported so far.

### CODE REVIEW

**Comment by cocreature** [comment]
@xldenis Hey, before I swamp you with more PRs that become relatively large as I keep pushing to them, how would you like to handle further development of this branch? I’m happy to keep making PRs until it’s ready but I feel like that mostly creates work for you with little benefit (since it’s still too early for in-depth reviews). Alternatively I could just directly push to some branch (either to the one in your repository or we can make one in the `llvm-hs` repository) and you either push directly to that branch as well or make PRs if you want me to look over something. In the latter case, commits should be relatively small to avoid duplicate work but I tend to do that anyway.

**Comment by xldenis** [comment]
I think that's going to be best you could probs just push directly to my branch on the main repo. Near the end we can do a single squash pass and avoid trashing the history with 100s of commits.

**Comment by cocreature** [comment]
> I think that's going to be best you could probs just push directly to my branch on the main repo.

In that case you are going to need to give me permissions, see https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by xldenis** [comment]
yep, I originally disabled it but I've re-enabled it. I'm going to merge your commit here though.

**Pull request merged**
